#include "tictactoe.h"

void TicTacToe::applyStyleSheet() {
    QString style;
    QString font;

    if (selectedTheme == "Dark") {
        font = "Segoe UI";
        style = QString(
                    "QWidget { "
                    "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
                    "stop:0 #1A1A1A, stop:0.5 #2D2D2D, stop:1 #1A1A1A); "
                    "color: #E0E0E0; "
                    "font-family: '%1'; "
                    "}"
                    "QLabel { "
                    "color: #E0E0E0; "
                    "font-weight: bold; "
                    "}"
                    "QLineEdit, QSpinBox { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #3D3D3D, stop:1 #2A2A2A); "
                    "color: #E0E0E0; "
                    "border: 2px solid #5D5D5D; "
                    "border-radius: 6px; "
                    "padding: 8px; "
                    "selection-background-color: #4A90E2; "
                    "}"
                    "QLineEdit:focus, QSpinBox:focus { "
                    "border: 2px solid #4A90E2; "
                    "box-shadow: 0px 0px 8px rgba(74, 144, 226, 0.5); "
                    "}"
                    "QPushButton { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #4D4D4D, stop:0.5 #3D3D3D, stop:1 #2D2D2D); "
                    "color: #E0E0E0; "
                    "border: 2px solid #5D5D5D; "
                    "border-radius: 6px; "
                    "padding: 10px; "
                    "font-weight: bold; "
                    "}"
                    "QPushButton:hover { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #5D5D5D, stop:1 #4D4D4D); "
                    "border: 2px solid #4A90E2; "
                    "box-shadow: 0px 0px 10px rgba(74, 144, 226, 0.3); "
                    "}"
                    "QPushButton:pressed { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #2D2D2D, stop:1 #3D3D3D); "
                    "border: 2px solid #4A90E2; "
                    "}"
                    "QTableWidget { "
                    "background-color: #2D2D2D; "
                    "color: #E0E0E0; "
                    "gridline-color: #5D5D5D; "
                    "border: 2px solid #4D4D4D; "
                    "border-radius: 6px; "
                    "}"
                    "QTableWidget::item:selected { "
                    "background-color: #4A90E2; "
                    "color: #FFFFFF; "
                    "}"
                    "QHeaderView::section { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #4D4D4D, stop:1 #3D3D3D); "
                    "color: #E0E0E0; "
                    "border: 1px solid #5D5D5D; "
                    "padding: 8px; "
                    "font-weight: bold; "
                    "}"
                    ).arg(font);

        scoreLabel->setStyleSheet(
            "QLabel { "
            "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
            "stop:0 #3D3D3D, stop:1 #2D2D2D); "
            "color: #E0E0E0; "
            "border: 2px solid #5D5D5D; "
            "border-radius: 10px; "
            "padding: 12px; "
            "font-family: 'Segoe UI'; "
            "font-weight: bold; "
            "}"
            );
    }

    else if (selectedTheme == "Blue") {
        font = "Calibri";
        style = QString(
                    "QWidget { "
                    "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
                    "stop:0 #0F1B3C, stop:0.5 #1E1E40, stop:1 #0F1B3C); "
                    "color: #FFFFFF; "
                    "font-family: '%1'; "
                    "}"
                    "QLabel { "
                    "color: #FFFFFF; "
                    "font-weight: bold; "
                    "text-shadow: 0px 0px 4px rgba(255, 255, 255, 0.3); "
                    "}"
                    "QLineEdit, QSpinBox { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #304070, stop:1 #1E2A50); "
                    "color: #FFFFFF; "
                    "border: 2px solid #506090; "
                    "border-radius: 8px; "
                    "padding: 8px; "
                    "selection-background-color: #7B68EE; "
                    "}"
                    "QLineEdit:focus, QSpinBox:focus { "
                    "border: 2px solid #7B68EE; "
                    "box-shadow: 0px 0px 12px rgba(123, 104, 238, 0.5); "
                    "}"
                    "QPushButton { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #4060A0, stop:0.5 #304070, stop:1 #1E2A50); "
                    "color: #FFFFFF; "
                    "border: 2px solid #506090; "
                    "border-radius: 8px; "
                    "padding: 10px; "
                    "font-weight: bold; "
                    "}"
                    "QPushButton:hover { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #5070C0, stop:1 #4060A0); "
                    "border: 2px solid #7B68EE; "
                    "box-shadow: 0px 0px 15px rgba(123, 104, 238, 0.4); "
                    "}"
                    "QPushButton:pressed { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #1E2A50, stop:1 #304070); "
                    "border: 2px solid #7B68EE; "
                    "}"
                    ).arg(font);

        scoreLabel->setStyleSheet(
            "QLabel { "
            "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
            "stop:0 #2B3A67, stop:1 #1E2A50); "
            "color: #FFFFFF; "
            "border: 2px solid #4060A0; "
            "border-radius: 10px; "
            "padding: 12px; "
            "font-family: 'Calibri'; "
            "font-weight: bold; "
            "text-shadow: 0px 0px 6px rgba(255, 255, 255, 0.3); "
            "}"
            );
    }

    else if (selectedTheme == "Plywood") {
        font = "Georgia";
        style = QString(
                    "QWidget { "
                    "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
                    "stop:0 #D2B48C, stop:0.3 #D7C4A3, stop:0.7 #DEB887, stop:1 #D2B48C); "
                    "color: #4E342E; "
                    "font-family: '%1'; "
                    "}"
                    "QLabel { "
                    "color: #4E342E; "
                    "font-weight: bold; "
                    "text-shadow: 0px 1px 2px rgba(255, 255, 255, 0.3); "
                    "}"
                    "QLineEdit, QSpinBox { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #F5F5DC, stop:1 #EFEBE9); "
                    "color: #4E342E; "
                    "border: 2px solid #8D6E63; "
                    "border-radius: 8px; "
                    "padding: 8px; "
                    "selection-background-color: #CD853F; "
                    "}"
                    "QLineEdit:focus, QSpinBox:focus { "
                    "border: 2px solid #A0522D; "
                    "box-shadow: 0px 0px 8px rgba(160, 82, 45, 0.4); "
                    "}"
                    "QPushButton { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #DEB887, stop:0.5 #BCAAA4, stop:1 #A0522D); "
                    "color: #3E2723; "
                    "border: 2px solid #8D6E63; "
                    "border-radius: 8px; "
                    "padding: 10px; "
                    "font-weight: bold; "
                    "text-shadow: 0px 1px 2px rgba(255, 255, 255, 0.2); "
                    "}"
                    "QPushButton:hover { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #F4A460, stop:1 #CD853F); "
                    "border: 2px solid #A0522D; "
                    "box-shadow: 0px 0px 10px rgba(160, 82, 45, 0.3); "
                    "}"
                    "QPushButton:pressed { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #A0522D, stop:1 #8D6E63); "
                    "color: #FFFFFF; "
                    "}"
                    ).arg(font);

        scoreLabel->setStyleSheet(
            "QLabel { "
            "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
            "stop:0 #F5F5DC, stop:1 #EFEBE9); "
            "color: #4E342E; "
            "border: 2px solid #8D6E63; "
            "border-radius: 12px; "
            "padding: 12px; "
            "font-family: 'Georgia'; "
            "font-weight: bold; "
            "text-shadow: 0px 1px 2px rgba(255, 255, 255, 0.4); "
            "}"
            );
    }

    else if (selectedTheme == "S.P.Q.R") {
        font = "Trajan Pro";
        style = QString(
                    "QWidget { "
                    "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
                    "stop:0 #4A0E0E, stop:0.3 #6E1414, stop:0.7 #8B0000, stop:1 #4A0E0E); "
                    "color: #FFD700; "
                    "font-family: '%1'; "
                    "}"
                    "QLabel { "
                    "color: #FFD700; "
                    "font-weight: bold; "
                    "text-shadow: 0px 0px 6px #FFD700; "
                    "}"
                    "QLineEdit, QSpinBox { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #9E1B1B, stop:1 #6E1414); "
                    "color: #FFD700; "
                    "border: 2px solid #B22222; "
                    "border-radius: 8px; "
                    "padding: 8px; "
                    "selection-background-color: #DC143C; "
                    "}"
                    "QLineEdit:focus, QSpinBox:focus { "
                    "border: 2px solid #FFD700; "
                    "box-shadow: 0px 0px 12px rgba(255, 215, 0, 0.5); "
                    "}"
                    "QPushButton { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #B22222, stop:0.5 #800000, stop:1 #4A0E0E); "
                    "color: #FFD700; "
                    "border: 2px solid #B22222; "
                    "border-radius: 8px; "
                    "padding: 10px; "
                    "font-weight: bold; "
                    "text-shadow: 0px 0px 4px #FFD700; "
                    "}"
                    "QPushButton:hover { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #DC143C, stop:1 #B22222); "
                    "border: 2px solid #FFD700; "
                    "box-shadow: 0px 0px 15px rgba(255, 215, 0, 0.4); "
                    "}"
                    "QPushButton:pressed { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #4A0E0E, stop:1 #800000); "
                    "border: 2px solid #FFD700; "
                    "}"
                    ).arg(font);

        scoreLabel->setStyleSheet(
            "QLabel { "
            "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
            "stop:0 #9E1B1B, stop:1 #6E1414); "
            "color: #FFD700; "
            "border: 2px solid #B22222; "
            "border-radius: 12px; "
            "padding: 12px; "
            "font-family: 'Trajan Pro'; "
            "font-weight: bold; "
            "text-shadow: 0px 0px 8px #FFD700; "
            "}"
            );
    }

    else if (selectedTheme == "Carthago") {
        font = "Palatino Linotype";
        style = QString(
                    "QWidget { "
                    "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
                    "stop:0 #2E1A35, stop:0.5 #3E1F47, stop:1 #2E1A35); "
                    "color: #FFFFFF; "
                    "font-family: '%1'; "
                    "}"
                    "QLabel { "
                    "color: #FFFFFF; "
                    "font-weight: bold; "
                    "text-shadow: 0px 0px 6px rgba(156, 77, 204, 0.6); "
                    "}"
                    "QLineEdit, QSpinBox { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #5C2E7E, stop:1 #3E1F47); "
                    "color: #FFFFFF; "
                    "border: 2px solid #8A4FAD; "
                    "border-radius: 8px; "
                    "padding: 8px; "
                    "selection-background-color: #9C4DCC; "
                    "}"
                    "QLineEdit:focus, QSpinBox:focus { "
                    "border: 2px solid #BA68C8; "
                    "box-shadow: 0px 0px 12px rgba(186, 104, 200, 0.5); "
                    "}"
                    "QPushButton { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #7E57C2, stop:0.5 #6A1B9A, stop:1 #4A148C); "
                    "color: #FFFFFF; "
                    "border: 2px solid #9C4DCC; "
                    "border-radius: 8px; "
                    "padding: 10px; "
                    "font-weight: bold; "
                    "text-shadow: 0px 0px 4px rgba(255, 255, 255, 0.3); "
                    "}"
                    "QPushButton:hover { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #9C4DCC, stop:1 #7E57C2); "
                    "border: 2px solid #BA68C8; "
                    "box-shadow: 0px 0px 15px rgba(186, 104, 200, 0.4); "
                    "}"
                    "QPushButton:pressed { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #4A148C, stop:1 #6A1B9A); "
                    "border: 2px solid #BA68C8; "
                    "}"
                    ).arg(font);

        scoreLabel->setStyleSheet(
            "QLabel { "
            "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
            "stop:0 #5C2E7E, stop:1 #3E1F47); "
            "color: #FFFFFF; "
            "border: 2px solid #9C4DCC; "
            "border-radius: 12px; "
            "padding: 12px; "
            "font-family: 'Palatino Linotype'; "
            "font-weight: bold; "
            "text-shadow: 0px 0px 8px rgba(156, 77, 204, 0.6); "
            "}"
            );
    }

    else if (selectedTheme == "Frosted Glass") {
        font = "Verdana";
        style = QString(
                    "QWidget { "
                    "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
                    "stop:0 #E0F7FA, stop:0.3 #B2EBF2, stop:0.7 #80DEEA, stop:1 #E0F7FA); "
                    "color: #003E57; "
                    "font-family: '%1'; "
                    "}"
                    "QLabel { "
                    "color: #003E57; "
                    "font-weight: bold; "
                    "text-shadow: 0px 1px 2px rgba(255, 255, 255, 0.8); "
                    "}"
                    "QLineEdit, QSpinBox { "
                    "background: rgba(255,255,255,0.8); "
                    "color: #003E57; "
                    "border: 2px solid #B0BEC5; "
                    "border-radius: 10px; "
                    "padding: 8px; "
                    "selection-background-color: #4DD0E1; "
                    "}"
                    "QLineEdit:focus, QSpinBox:focus { "
                    "border: 2px solid #00BCD4; "
                    "box-shadow: 0px 0px 12px rgba(0, 188, 212, 0.4); "
                    "background: rgba(255,255,255,0.95); "
                    "}"
                    "QPushButton { "
                    "background: rgba(255,255,255,0.9); "
                    "color: #004D60; "
                    "border: 2px solid #90A4AE; "
                    "border-radius: 10px; "
                    "padding: 10px; "
                    "font-weight: bold; "
                    "text-shadow: 0px 1px 2px rgba(255, 255, 255, 0.5); "
                    "}"
                    "QPushButton:hover { "
                    "background: rgba(255,255,255,1.0); "
                    "border: 2px solid #00BCD4; "
                    "box-shadow: 0px 0px 15px rgba(0, 188, 212, 0.3); "
                    "}"
                    "QPushButton:pressed { "
                    "background: #CFD8DC; "
                    "border: 2px solid #00BCD4; "
                    "}"
                    ).arg(font);

        scoreLabel->setStyleSheet(
            "QLabel { "
            "background: rgba(255,255,255,0.7); "
            "color: #004D60; "
            "border: 2px solid #B0BEC5; "
            "border-radius: 15px; "
            "padding: 12px; "
            "font-family: 'Verdana'; "
            "font-weight: bold; "
            "text-shadow: 0px 1px 2px rgba(255, 255, 255, 0.8); "
            "}"
            );
    }

    else if (selectedTheme == "Ancient Egypt") {
        font = "Papyrus";
        style = QString(
                    "QWidget { "
                    "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
                    "stop:0 #F4E4BC, stop:0.3 #F5E5B8, stop:0.7 #E6D690, stop:1 #F4E4BC); "
                    "color: #5C432E; "
                    "font-family: '%1'; "
                    "}"
                    "QLabel { "
                    "color: #5C432E; "
                    "font-weight: bold; "
                    "text-shadow: 0px 1px 3px rgba(255, 215, 0, 0.4); "
                    "}"
                    "QLineEdit, QSpinBox { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #FFF8DC, stop:1 #F9F3D2); "
                    "color: #5C432E; "
                    "border: 2px solid #CBB67C; "
                    "border-radius: 8px; "
                    "padding: 8px; "
                    "selection-background-color: #DAA520; "
                    "}"
                    "QLineEdit:focus, QSpinBox:focus { "
                    "border: 2px solid #B8860B; "
                    "box-shadow: 0px 0px 10px rgba(184, 134, 11, 0.4); "
                    "}"
                    "QPushButton { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #F0E68C, stop:0.5 #E5C56E, stop:1 #DAA520); "
                    "color: #4E342E; "
                    "border: 2px solid #B79850; "
                    "border-radius: 8px; "
                    "padding: 10px; "
                    "font-weight: bold; "
                    "text-shadow: 0px 1px 2px rgba(255, 215, 0, 0.3); "
                    "}"
                    "QPushButton:hover { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #FFD700, stop:1 #F0E68C); "
                    "border: 2px solid #B8860B; "
                    "box-shadow: 0px 0px 12px rgba(255, 215, 0, 0.4); "
                    "}"
                    "QPushButton:pressed { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #B8860B, stop:1 #DAA520); "
                    "color: #FFFFFF; "
                    "}"
                    ).arg(font);

        scoreLabel->setStyleSheet(
            "QLabel { "
            "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
            "stop:0 #FFF8DC, stop:1 #F9F3D2); "
            "color: #5C432E; "
            "border: 2px solid #CBB67C; "
            "border-radius: 12px; "
            "padding: 12px; "
            "font-family: 'Papyrus'; "
            "font-weight: bold; "
            "text-shadow: 0px 1px 3px rgba(255, 215, 0, 0.4); "
            "}"
            );
    }

    else if (selectedTheme == "Seljuk Empire") {
        font = "Noto Naskh Arabic";
        style = QString(
                    "QWidget { "
                    "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
                    "stop:0 #0A2A4A, stop:0.5 #0D3B66, stop:1 #0A2A4A); "
                    "color: #FAF0E6; "
                    "font-family: '%1'; "
                    "}"
                    "QLabel { "
                    "color: #FAF0E6; "
                    "font-weight: bold; "
                    "text-shadow: 0px 0px 6px rgba(99, 164, 255, 0.5); "
                    "}"
                    "QLineEdit, QSpinBox { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #1E5A96, stop:1 #145DA0); "
                    "color: #FFFFFF; "
                    "border: 2px solid #1E81B0; "
                    "border-radius: 8px; "
                    "padding: 8px; "
                    "selection-background-color: #63A4FF; "
                    "}"
                    "QLineEdit:focus, QSpinBox:focus { "
                    "border: 2px solid #63A4FF; "
                    "box-shadow: 0px 0px 12px rgba(99, 164, 255, 0.5); "
                    "}"
                    "QPushButton { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #2196F3, stop:0.5 #1E81B0, stop:1 #145DA0); "
                    "color: #FFFFFF; "
                    "border: 2px solid #63A4FF; "
                    "border-radius: 8px; "
                    "padding: 10px; "
                    "font-weight: bold; "
                    "text-shadow: 0px 0px 4px rgba(255, 255, 255, 0.3); "
                    "}"
                    "QPushButton:hover { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #63A4FF, stop:1 #2196F3); "
                    "border: 2px solid #90CAF9; "
                    "box-shadow: 0px 0px 15px rgba(99, 164, 255, 0.4); "
                    "}"
                    "QPushButton:pressed { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #145DA0, stop:1 #1E81B0); "
                    "border: 2px solid #90CAF9; "
                    "}"
                    ).arg(font);

        scoreLabel->setStyleSheet(
            "QLabel { "
            "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
            "stop:0 #1E5A96, stop:1 #145DA0); "
            "color: #FFFFFF; "
            "border: 2px solid #63A4FF; "
            "border-radius: 12px; "
            "padding: 12px; "
            "font-family: 'Noto Naskh Arabic'; "
            "font-weight: bold; "
            "text-shadow: 0px 0px 8px rgba(99, 164, 255, 0.5); "
            "}"
            );
    }

    else if (selectedTheme == "8-Bit") {
        font = "Courier New";
        style = QString(
                    "QWidget { "
                    "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
                    "stop:0 #1A1A1A, stop:0.5 #282828, stop:1 #1A1A1A); "
                    "color: #FFD700; "
                    "font-family: '%1'; "
                    "}"
                    "QLabel { "
                    "color: #FFD700; "
                    "font-weight: bold; "
                    "text-shadow: 0px 0px 4px #FFD700; "
                    "}"
                    "QLineEdit, QSpinBox { "
                    "background: #404040; "
                    "color: #FFD700; "
                    "border: 3px solid #FFD700; "
                    "border-radius: 0px; "
                    "padding: 8px; "
                    "selection-background-color: #FF6B35; "
                    "}"
                    "QLineEdit:focus, QSpinBox:focus { "
                    "border: 3px solid #FF6B35; "
                    "box-shadow: 0px 0px 8px rgba(255, 107, 53, 0.6); "
                    "}"
                    "QPushButton { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #606060, stop:0.5 #404040, stop:1 #202020); "
                    "color: #FFD700; "
                    "border: 3px solid #FFD700; "
                    "border-radius: 0px; "
                    "padding: 10px; "
                    "font-weight: bold; "
                    "text-shadow: 0px 0px 3px #FFD700; "
                    "}"
                    "QPushButton:hover { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #808080, stop:1 #606060); "
                    "border: 3px solid #FF6B35; "
                    "color: #FF6B35; "
                    "text-shadow: 0px 0px 4px #FF6B35; "
                    "}"
                    "QPushButton:pressed { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #202020, stop:1 #404040); "
                    "border: 3px solid #FF6B35; "
                    "}"
                    ).arg(font);

        scoreLabel->setStyleSheet(
            "QLabel { "
            "background: #303030; "
            "color: #FFD700; "
            "border: 3px solid #FFD700; "
            "border-radius: 0px; "
            "padding: 12px; "
            "font-family: 'Courier New'; "
            "font-weight: bold; "
            "text-shadow: 0px 0px 6px #FFD700; "
            "}"
            );
    }
    else if (selectedTheme == "Cyber Enhanced") {
        font = "Consolas";
        style = QString(
                    "QWidget { "
                    "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
                    "stop:0 #0A0A0A, stop:0.3 #1A0A1A, stop:0.7 #0A1A1A, stop:1 #0F0F0F); "
                    "color: #00FFEA; "
                    "font-family: '%1'; "
                    "}"
                    "QLabel { "
                    "color: #00FFEA; "
                    "font-weight: bold; "
                    "text-shadow: 0px 0px 8px #00FFEA; "
                    "}"
                    "QLineEdit, QSpinBox { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #1F1F1F, stop:1 #2A2A2A); "
                    "color: #00FFEA; "
                    "border: 2px solid #00FFEA; "
                    "border-radius: 8px; "
                    "padding: 8px; "
                    "selection-background-color: #FF0080; "
                    "selection-color: #FFFFFF; "
                    "}"
                    "QLineEdit:focus, QSpinBox:focus { "
                    "border: 2px solid #FF0080; "
                    "box-shadow: 0px 0px 12px #FF0080; "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #2A1A2A, stop:1 #1F1F2F); "
                    "}"
                    "QPushButton { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #2A2A2A, stop:0.5 #1F1F1F, stop:1 #0F0F0F); "
                    "color: #00FFEA; "
                    "border: 2px solid #00FFEA; "
                    "border-radius: 8px; "
                    "padding: 10px; "
                    "font-weight: bold; "
                    "text-shadow: 0px 0px 6px #00FFEA; "
                    "}"
                    "QPushButton:hover { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #00FFEA, stop:0.5 #008B8B, stop:1 #006666); "
                    "color: #000000; "
                    "border: 2px solid #FF0080; "
                    "text-shadow: 0px 0px 8px #000000; "
                    "box-shadow: 0px 0px 15px #00FFEA; "
                    "}"
                    "QPushButton:pressed { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #FF0080, stop:0.5 #CC0066, stop:1 #990044); "
                    "color: #FFFFFF; "
                    "border: 2px solid #FFFFFF; "
                    "text-shadow: 0px 0px 6px #FFFFFF; "
                    "}"
                    "QComboBox { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #1F1F1F, stop:1 #2A2A2A); "
                    "color: #00FFEA; "
                    "border: 2px solid #00FFEA; "
                    "border-radius: 8px; "
                    "padding: 6px; "
                    "selection-background-color: #FF0080; "
                    "}"
                    "QComboBox::drop-down { "
                    "border: none; "
                    "background: #FF0080; "
                    "border-radius: 4px; "
                    "}"
                    "QComboBox::down-arrow { "
                    "image: none; "
                    "border: 2px solid #00FFEA; "
                    "width: 8px; "
                    "height: 8px; "
                    "}"
                    "QTableWidget { "
                    "background-color: #0F0F0F; "
                    "color: #00FFEA; "
                    "gridline-color: #FF0080; "
                    "border: 2px solid #00FFEA; "
                    "border-radius: 8px; "
                    "}"
                    "QTableWidget::item { "
                    "padding: 8px; "
                    "border-bottom: 1px solid #333333; "
                    "}"
                    "QTableWidget::item:selected { "
                    "background-color: #FF0080; "
                    "color: #FFFFFF; "
                    "}"
                    "QHeaderView::section { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #2A2A2A, stop:1 #1F1F1F); "
                    "color: #00FFEA; "
                    "border: 1px solid #FF0080; "
                    "padding: 8px; "
                    "font-weight: bold; "
                    "text-shadow: 0px 0px 4px #00FFEA; "
                    "}"
                    "QScrollBar:vertical { "
                    "background: #1F1F1F; "
                    "width: 12px; "
                    "border: 1px solid #00FFEA; "
                    "border-radius: 6px; "
                    "}"
                    "QScrollBar::handle:vertical { "
                    "background: qlineargradient(x1:0, y1:0, x2:1, y2:0, "
                    "stop:0 #00FFEA, stop:1 #FF0080); "
                    "border-radius: 5px; "
                    "min-height: 20px; "
                    "}"
                    "QScrollBar::handle:vertical:hover { "
                    "background: #FF0080; "
                    "}"
                    ).arg(font);

        scoreLabel->setStyleSheet(
            "QLabel { "
            "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
            "stop:0 #1F1F1F, stop:0.5 #2A1A2A, stop:1 #1A2A2A); "
            "color: #00FFEA; "
            "border: 2px solid #00FFEA; "
            "border-radius: 12px; "
            "padding: 15px; "
            "font-family: 'Consolas'; "
            "font-weight: bold; "
            "text-shadow: 0px 0px 10px #00FFEA; "
            "box-shadow: inset 0px 0px 20px rgba(0, 255, 234, 0.3); "
            "}"
            );
    } else {
        // Light Theme (Default)
        font = "Segoe UI";
        style = QString(
                    "QWidget { "
                    "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
                    "stop:0 #FAFAFA, stop:0.5 #FFFFFF, stop:1 #FAFAFA); "
                    "color: #333333; "
                    "font-family: '%1'; "
                    "}"
                    "QLabel { "
                    "color: #333333; "
                    "font-weight: bold; "
                    "}"
                    "QLineEdit, QSpinBox { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #FFFFFF, stop:1 #F5F5F5); "
                    "color: #333333; "
                    "border: 2px solid #CCCCCC; "
                    "border-radius: 6px; "
                    "padding: 8px; "
                    "selection-background-color: #4A90E2; "
                    "selection-color: #FFFFFF; "
                    "}"
                    "QLineEdit:focus, QSpinBox:focus { "
                    "border: 2px solid #4A90E2; "
                    "box-shadow: 0px 0px 8px rgba(74, 144, 226, 0.3); "
                    "}"
                    "QPushButton { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #FFFFFF, stop:0.5 #F5F5F5, stop:1 #E0E0E0); "
                    "color: #333333; "
                    "border: 2px solid #CCCCCC; "
                    "border-radius: 6px; "
                    "padding: 10px; "
                    "font-weight: bold; "
                    "}"
                    "QPushButton:hover { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #E3F2FD, stop:1 #BBDEFB); "
                    "border: 2px solid #4A90E2; "
                    "box-shadow: 0px 0px 10px rgba(74, 144, 226, 0.2); "
                    "}"
                    "QPushButton:pressed { "
                    "background: qlineargradient(x1:0, y1:0, x2:0, y2:1, "
                    "stop:0 #BBDEFB, stop:1 #E3F2FD); "
                    "border: 2px solid #4A90E2; "
                    "}"
                    ).arg(font);

        scoreLabel->setStyleSheet(
            "QLabel { "
            "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, "
            "stop:0 #FFFFFF, stop:1 #F5F5F5); "
            "color: #333333; "
            "border: 2px solid #CCCCCC; "
            "border-radius: 10px; "
            "padding: 12px; "
            "font-family: 'Segoe UI'; "
            "font-weight: bold; "
            "}"
            );
    }

    setStyleSheet(style);

    // Enhanced button styling for game board
    for (int i = 0; i < 9; ++i) {
        QPushButton *button = qobject_cast<QPushButton *>(buttonGroup->button(i));
        if (button) {
            button->setStyleSheet(button->styleSheet() +
                                  QString(" QPushButton { "
                                          "font-weight: bold; "
                                          "font-size: 28px; "
                                          "padding: 15px; "
                                          "font-family: '%1'; "
                                          "border-width: 3px; "
                                          "}").arg(font));
        }
    }
}
