name: TicTacToe-CI-CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Update package lists
      run: sudo apt-get update
      
    - name: Install Qt and build dependencies
      run: |
        sudo apt-get install -y build-essential qt6-base-dev qt6-base-dev-tools qt6-sql-dev cmake
        
    - name: Create CMakeLists.txt
      run: |
        cat > CMakeLists.txt << 'EOF'
        cmake_minimum_required(VERSION 3.16)
        project(tictactoe)
        
        set(CMAKE_CXX_STANDARD 17)
        set(CMAKE_CXX_STANDARD_REQUIRED ON)
        
        find_package(Qt6 REQUIRED COMPONENTS Core Widgets Sql)
        
        file(GLOB SOURCES "*.cpp" "*.h")
        add_executable(tictactoe ${SOURCES})
        
        target_link_libraries(tictactoe Qt6::Core Qt6::Widgets Qt6::Sql)
        EOF
        
    - name: Build Qt application
      run: |
        mkdir build
        cd build
        cmake ..
        make
        
    - name: Run simple test
      run: |
        cd build
        ./tictactoe || true
        
    - name: Upload built binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: tictactoe
        path: build/tictactoe
