# File: .github/workflows/qt-cpp-ci.yml

name: Qt C++ CI/CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  pull_request:
    branches: [ main ]

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'

      - name: Build project with qmake
        run: |
          qmake
          make

      - name: Upload executable as artifact
        uses: actions/upload-artifact@v4
        with:
          name: QtApp
          path: ./QtTicTacToe  # replace with your binary name if different

      - name: Create GitHub Release (only on tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: ./QtTicTacToe  # replace if different
