name: TicTacToe Qt CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Qt dependencies
      run: |
        # Install essential build tools and Qt development libraries
        sudo apt-get update
        sudo apt-get install -y build-essential qtbase5-dev libqt5sql5-sqlite

    - name: Generate Makefile using qmake
      # qmake reads your project file (.pro) and generates a Makefile
      # Assumes your .pro file is in the root directory. If not, adjust the path.
      run: qmake TicTacToe.pro

    - name: Build project
      # make compiles the source files, links libraries, and creates the executable
      run: make

    - name: Run simple test (optional, for CLI applications)
      # For a GUI application like TicTacToe, a simple execution might not
      # fully test functionality. You might need automated UI tests for that.
      # The '|| true' ensures the CI step doesn't fail if the app exits non-zero,
      # which can happen with GUI apps that don't have a clean exit for CI.
      # Remove '|| true' if you expect a specific exit code for success.
      run: ./tictactoe || true

    - name: Upload built binary as artifact
      uses: actions/upload-artifact@v4
      with:
        name: tictactoe-qt-build
        path: tictactoe # The name of your executable generated by 'make'
        # If your executable has a different name, update this path.
