name: TicTacToe-CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: sudo apt-get install -y build-essential

    - name: Build project
      run: |
        g++ *.cpp -o tictactoe

    - name: Run simple test
      run: |
        ./tictactoe || true
